/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.9.4.0 (NJsonSchema v10.3.1.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import * as ng from 'angular';

export class DomainEventsClient {
    private baseUrl: string | undefined = undefined;
    private http: ng.IHttpService;
    private q: ng.IQService;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor($http: ng.IHttpService, $q: ng.IQService, baseUrl?: string) {
        this.http = $http;
        this.q = $q;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getDetails(id: string): ng.IPromise<DomainEventDetails | null> {
        let url_ = this.baseUrl + "/api/DomainEvents/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "GET",
            transformResponse: [],
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http(options_).then((_response) => {
            return this.processGetDetails(_response);
        }, (_response) => {
            if (_response.status)
                return this.processGetDetails(_response);
            throw _response;
        });
    }

    protected processGetDetails(response: any): ng.IPromise<DomainEventDetails | null> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? DomainEventDetails.fromJS(resultData200) : <any>null;
            return this.q.resolve(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<DomainEventDetails | null>(<any>null);
    }

    delete(id: string): ng.IPromise<void> {
        let url_ = this.baseUrl + "/api/DomainEvents/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "DELETE",
            transformResponse: [],
            headers: {
            }
        };

        return this.http(options_).then((_response) => {
            return this.processDelete(_response);
        }, (_response) => {
            if (_response.status)
                return this.processDelete(_response);
            throw _response;
        });
    }

    protected processDelete(response: any): ng.IPromise<void> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            return this.q.resolve<void>(<any>null);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<void>(<any>null);
    }

    generate(id: string, templateId: string): ng.IPromise<GeneratedCodeOfDomainEvent | null> {
        let url_ = this.baseUrl + "/api/DomainEvents/{id}/generate/{templateId}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (templateId === undefined || templateId === null)
            throw new Error("The parameter 'templateId' must be defined.");
        url_ = url_.replace("{templateId}", encodeURIComponent("" + templateId));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "GET",
            transformResponse: [],
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http(options_).then((_response) => {
            return this.processGenerate(_response);
        }, (_response) => {
            if (_response.status)
                return this.processGenerate(_response);
            throw _response;
        });
    }

    protected processGenerate(response: any): ng.IPromise<GeneratedCodeOfDomainEvent | null> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? GeneratedCodeOfDomainEvent.fromJS(resultData200) : <any>null;
            return this.q.resolve(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<GeneratedCodeOfDomainEvent | null>(<any>null);
    }

    addProperty(id: string, model: AddProperty | null): ng.IPromise<void> {
        let url_ = this.baseUrl + "/api/DomainEvents/{id}/properties";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(model);

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "PUT",
            data: content_,
            transformResponse: [],
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http(options_).then((_response) => {
            return this.processAddProperty(_response);
        }, (_response) => {
            if (_response.status)
                return this.processAddProperty(_response);
            throw _response;
        });
    }

    protected processAddProperty(response: any): ng.IPromise<void> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            return this.q.resolve<void>(<any>null);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<void>(<any>null);
    }

    removeProperty(id: string, name: string | null): ng.IPromise<void> {
        let url_ = this.baseUrl + "/api/DomainEvents/{id}/properties/{name}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (name === undefined || name === null)
            throw new Error("The parameter 'name' must be defined.");
        url_ = url_.replace("{name}", encodeURIComponent("" + name));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "DELETE",
            transformResponse: [],
            headers: {
            }
        };

        return this.http(options_).then((_response) => {
            return this.processRemoveProperty(_response);
        }, (_response) => {
            if (_response.status)
                return this.processRemoveProperty(_response);
            throw _response;
        });
    }

    protected processRemoveProperty(response: any): ng.IPromise<void> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            return this.q.resolve<void>(<any>null);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<void>(<any>null);
    }
}

export class EntitiesClient {
    private baseUrl: string | undefined = undefined;
    private http: ng.IHttpService;
    private q: ng.IQService;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor($http: ng.IHttpService, $q: ng.IQService, baseUrl?: string) {
        this.http = $http;
        this.q = $q;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getDetails(id: string): ng.IPromise<EntityDetails | null> {
        let url_ = this.baseUrl + "/api/Entities/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "GET",
            transformResponse: [],
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http(options_).then((_response) => {
            return this.processGetDetails(_response);
        }, (_response) => {
            if (_response.status)
                return this.processGetDetails(_response);
            throw _response;
        });
    }

    protected processGetDetails(response: any): ng.IPromise<EntityDetails | null> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? EntityDetails.fromJS(resultData200) : <any>null;
            return this.q.resolve(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<EntityDetails | null>(<any>null);
    }

    delete(id: string): ng.IPromise<void> {
        let url_ = this.baseUrl + "/api/Entities/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "DELETE",
            transformResponse: [],
            headers: {
            }
        };

        return this.http(options_).then((_response) => {
            return this.processDelete(_response);
        }, (_response) => {
            if (_response.status)
                return this.processDelete(_response);
            throw _response;
        });
    }

    protected processDelete(response: any): ng.IPromise<void> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            return this.q.resolve<void>(<any>null);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<void>(<any>null);
    }

    generate(id: string, templateId: string): ng.IPromise<GeneratedCodeOfEntity | null> {
        let url_ = this.baseUrl + "/api/Entities/{id}/generate/{templateId}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (templateId === undefined || templateId === null)
            throw new Error("The parameter 'templateId' must be defined.");
        url_ = url_.replace("{templateId}", encodeURIComponent("" + templateId));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "GET",
            transformResponse: [],
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http(options_).then((_response) => {
            return this.processGenerate(_response);
        }, (_response) => {
            if (_response.status)
                return this.processGenerate(_response);
            throw _response;
        });
    }

    protected processGenerate(response: any): ng.IPromise<GeneratedCodeOfEntity | null> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? GeneratedCodeOfEntity.fromJS(resultData200) : <any>null;
            return this.q.resolve(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<GeneratedCodeOfEntity | null>(<any>null);
    }

    create(model: CreateType | null): ng.IPromise<Entity | null> {
        let url_ = this.baseUrl + "/api/Entities";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(model);

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "POST",
            data: content_,
            transformResponse: [],
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http(options_).then((_response) => {
            return this.processCreate(_response);
        }, (_response) => {
            if (_response.status)
                return this.processCreate(_response);
            throw _response;
        });
    }

    protected processCreate(response: any): ng.IPromise<Entity | null> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? Entity.fromJS(resultData200) : <any>null;
            return this.q.resolve(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<Entity | null>(<any>null);
    }

    addProperty(id: string, model: AddProperty | null): ng.IPromise<void> {
        let url_ = this.baseUrl + "/api/Entities/{id}/properties";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(model);

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "PUT",
            data: content_,
            transformResponse: [],
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http(options_).then((_response) => {
            return this.processAddProperty(_response);
        }, (_response) => {
            if (_response.status)
                return this.processAddProperty(_response);
            throw _response;
        });
    }

    protected processAddProperty(response: any): ng.IPromise<void> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            return this.q.resolve<void>(<any>null);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<void>(<any>null);
    }

    removeProperty(id: string, name: string | null): ng.IPromise<void> {
        let url_ = this.baseUrl + "/api/Entities/{id}/properties/{name}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (name === undefined || name === null)
            throw new Error("The parameter 'name' must be defined.");
        url_ = url_.replace("{name}", encodeURIComponent("" + name));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "DELETE",
            transformResponse: [],
            headers: {
            }
        };

        return this.http(options_).then((_response) => {
            return this.processRemoveProperty(_response);
        }, (_response) => {
            if (_response.status)
                return this.processRemoveProperty(_response);
            throw _response;
        });
    }

    protected processRemoveProperty(response: any): ng.IPromise<void> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            return this.q.resolve<void>(<any>null);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<void>(<any>null);
    }

    addDomainEvent(id: string, model: AddDomainEvent | null): ng.IPromise<void> {
        let url_ = this.baseUrl + "/api/Entities/{id}/domainEvents";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(model);

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "PUT",
            data: content_,
            transformResponse: [],
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http(options_).then((_response) => {
            return this.processAddDomainEvent(_response);
        }, (_response) => {
            if (_response.status)
                return this.processAddDomainEvent(_response);
            throw _response;
        });
    }

    protected processAddDomainEvent(response: any): ng.IPromise<void> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            return this.q.resolve<void>(<any>null);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<void>(<any>null);
    }

    addRelation(id: string, model: AddRelation | null): ng.IPromise<void> {
        let url_ = this.baseUrl + "/api/Entities/{id}/relations";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(model);

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "PUT",
            data: content_,
            transformResponse: [],
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http(options_).then((_response) => {
            return this.processAddRelation(_response);
        }, (_response) => {
            if (_response.status)
                return this.processAddRelation(_response);
            throw _response;
        });
    }

    protected processAddRelation(response: any): ng.IPromise<void> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            return this.q.resolve<void>(<any>null);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<void>(<any>null);
    }

    removeRelation(id: string, name: string | null): ng.IPromise<void> {
        let url_ = this.baseUrl + "/api/Entities/{id}/relations/{name}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (name === undefined || name === null)
            throw new Error("The parameter 'name' must be defined.");
        url_ = url_.replace("{name}", encodeURIComponent("" + name));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "DELETE",
            transformResponse: [],
            headers: {
            }
        };

        return this.http(options_).then((_response) => {
            return this.processRemoveRelation(_response);
        }, (_response) => {
            if (_response.status)
                return this.processRemoveRelation(_response);
            throw _response;
        });
    }

    protected processRemoveRelation(response: any): ng.IPromise<void> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            return this.q.resolve<void>(<any>null);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<void>(<any>null);
    }
}

export class ModulesClient {
    private baseUrl: string | undefined = undefined;
    private http: ng.IHttpService;
    private q: ng.IQService;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor($http: ng.IHttpService, $q: ng.IQService, baseUrl?: string) {
        this.http = $http;
        this.q = $q;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    get(): ng.IPromise<Module[] | null> {
        let url_ = this.baseUrl + "/api/Modules";
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "GET",
            transformResponse: [],
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http(options_).then((_response) => {
            return this.processGet(_response);
        }, (_response) => {
            if (_response.status)
                return this.processGet(_response);
            throw _response;
        });
    }

    protected processGet(response: any): ng.IPromise<Module[] | null> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(Module.fromJS(item));
            }
            return this.q.resolve(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<Module[] | null>(<any>null);
    }

    create(model: CreateModule | null): ng.IPromise<Module | null> {
        let url_ = this.baseUrl + "/api/Modules";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(model);

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "POST",
            data: content_,
            transformResponse: [],
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http(options_).then((_response) => {
            return this.processCreate(_response);
        }, (_response) => {
            if (_response.status)
                return this.processCreate(_response);
            throw _response;
        });
    }

    protected processCreate(response: any): ng.IPromise<Module | null> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? Module.fromJS(resultData200) : <any>null;
            return this.q.resolve(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<Module | null>(<any>null);
    }

    generate(id: string, templateId: string): ng.IPromise<GeneratedCodeOfModule | null> {
        let url_ = this.baseUrl + "/api/Modules/{id}/generate/{templateId}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (templateId === undefined || templateId === null)
            throw new Error("The parameter 'templateId' must be defined.");
        url_ = url_.replace("{templateId}", encodeURIComponent("" + templateId));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "GET",
            transformResponse: [],
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http(options_).then((_response) => {
            return this.processGenerate(_response);
        }, (_response) => {
            if (_response.status)
                return this.processGenerate(_response);
            throw _response;
        });
    }

    protected processGenerate(response: any): ng.IPromise<GeneratedCodeOfModule | null> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? GeneratedCodeOfModule.fromJS(resultData200) : <any>null;
            return this.q.resolve(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<GeneratedCodeOfModule | null>(<any>null);
    }

    delete(id: string): ng.IPromise<void> {
        let url_ = this.baseUrl + "/api/Modules/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "DELETE",
            transformResponse: [],
            headers: {
            }
        };

        return this.http(options_).then((_response) => {
            return this.processDelete(_response);
        }, (_response) => {
            if (_response.status)
                return this.processDelete(_response);
            throw _response;
        });
    }

    protected processDelete(response: any): ng.IPromise<void> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            return this.q.resolve<void>(<any>null);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<void>(<any>null);
    }
}

export class TemplatesClient {
    private baseUrl: string | undefined = undefined;
    private http: ng.IHttpService;
    private q: ng.IQService;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor($http: ng.IHttpService, $q: ng.IQService, baseUrl?: string) {
        this.http = $http;
        this.q = $q;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getByMetaType(metaType: MetaType): ng.IPromise<Template[] | null> {
        let url_ = this.baseUrl + "/api/Templates?";
        if (metaType === undefined || metaType === null)
            throw new Error("The parameter 'metaType' must be defined and cannot be null.");
        else
            url_ += "metaType=" + encodeURIComponent("" + metaType) + "&";
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "GET",
            transformResponse: [],
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http(options_).then((_response) => {
            return this.processGetByMetaType(_response);
        }, (_response) => {
            if (_response.status)
                return this.processGetByMetaType(_response);
            throw _response;
        });
    }

    protected processGetByMetaType(response: any): ng.IPromise<Template[] | null> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(Template.fromJS(item));
            }
            return this.q.resolve(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<Template[] | null>(<any>null);
    }

    create(model: CreateTemplate | null): ng.IPromise<Template | null> {
        let url_ = this.baseUrl + "/api/Templates";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(model);

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "POST",
            data: content_,
            transformResponse: [],
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http(options_).then((_response) => {
            return this.processCreate(_response);
        }, (_response) => {
            if (_response.status)
                return this.processCreate(_response);
            throw _response;
        });
    }

    protected processCreate(response: any): ng.IPromise<Template | null> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? Template.fromJS(resultData200) : <any>null;
            return this.q.resolve(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<Template | null>(<any>null);
    }

    getById(id: string): ng.IPromise<Template | null> {
        let url_ = this.baseUrl + "/api/Templates/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "GET",
            transformResponse: [],
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http(options_).then((_response) => {
            return this.processGetById(_response);
        }, (_response) => {
            if (_response.status)
                return this.processGetById(_response);
            throw _response;
        });
    }

    protected processGetById(response: any): ng.IPromise<Template | null> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? Template.fromJS(resultData200) : <any>null;
            return this.q.resolve(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<Template | null>(<any>null);
    }

    update(id: string, model: UpdateTemplate | null): ng.IPromise<Template | null> {
        let url_ = this.baseUrl + "/api/Templates/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(model);

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "PUT",
            data: content_,
            transformResponse: [],
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http(options_).then((_response) => {
            return this.processUpdate(_response);
        }, (_response) => {
            if (_response.status)
                return this.processUpdate(_response);
            throw _response;
        });
    }

    protected processUpdate(response: any): ng.IPromise<Template | null> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? Template.fromJS(resultData200) : <any>null;
            return this.q.resolve(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<Template | null>(<any>null);
    }

    delete(id: string): ng.IPromise<void> {
        let url_ = this.baseUrl + "/api/Templates/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "DELETE",
            transformResponse: [],
            headers: {
            }
        };

        return this.http(options_).then((_response) => {
            return this.processDelete(_response);
        }, (_response) => {
            if (_response.status)
                return this.processDelete(_response);
            throw _response;
        });
    }

    protected processDelete(response: any): ng.IPromise<void> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            return this.q.resolve<void>(<any>null);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<void>(<any>null);
    }
}

export class ValueObjectsClient {
    private baseUrl: string | undefined = undefined;
    private http: ng.IHttpService;
    private q: ng.IQService;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor($http: ng.IHttpService, $q: ng.IQService, baseUrl?: string) {
        this.http = $http;
        this.q = $q;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getDetails(id: string): ng.IPromise<ValueObjectDetails | null> {
        let url_ = this.baseUrl + "/api/ValueObjects/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "GET",
            transformResponse: [],
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http(options_).then((_response) => {
            return this.processGetDetails(_response);
        }, (_response) => {
            if (_response.status)
                return this.processGetDetails(_response);
            throw _response;
        });
    }

    protected processGetDetails(response: any): ng.IPromise<ValueObjectDetails | null> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? ValueObjectDetails.fromJS(resultData200) : <any>null;
            return this.q.resolve(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<ValueObjectDetails | null>(<any>null);
    }

    delete(id: string): ng.IPromise<void> {
        let url_ = this.baseUrl + "/api/ValueObjects/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "DELETE",
            transformResponse: [],
            headers: {
            }
        };

        return this.http(options_).then((_response) => {
            return this.processDelete(_response);
        }, (_response) => {
            if (_response.status)
                return this.processDelete(_response);
            throw _response;
        });
    }

    protected processDelete(response: any): ng.IPromise<void> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            return this.q.resolve<void>(<any>null);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<void>(<any>null);
    }

    generate(id: string, templateId: string): ng.IPromise<GeneratedCodeOfValueObject | null> {
        let url_ = this.baseUrl + "/api/ValueObjects/{id}/generate/{templateId}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (templateId === undefined || templateId === null)
            throw new Error("The parameter 'templateId' must be defined.");
        url_ = url_.replace("{templateId}", encodeURIComponent("" + templateId));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "GET",
            transformResponse: [],
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http(options_).then((_response) => {
            return this.processGenerate(_response);
        }, (_response) => {
            if (_response.status)
                return this.processGenerate(_response);
            throw _response;
        });
    }

    protected processGenerate(response: any): ng.IPromise<GeneratedCodeOfValueObject | null> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? GeneratedCodeOfValueObject.fromJS(resultData200) : <any>null;
            return this.q.resolve(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<GeneratedCodeOfValueObject | null>(<any>null);
    }

    create(model: CreateType | null): ng.IPromise<ValueObject | null> {
        let url_ = this.baseUrl + "/api/ValueObjects";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(model);

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "POST",
            data: content_,
            transformResponse: [],
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http(options_).then((_response) => {
            return this.processCreate(_response);
        }, (_response) => {
            if (_response.status)
                return this.processCreate(_response);
            throw _response;
        });
    }

    protected processCreate(response: any): ng.IPromise<ValueObject | null> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? ValueObject.fromJS(resultData200) : <any>null;
            return this.q.resolve(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<ValueObject | null>(<any>null);
    }

    addProperty(id: string, model: AddProperty | null): ng.IPromise<void> {
        let url_ = this.baseUrl + "/api/ValueObjects/{id}/properties";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(model);

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "PUT",
            data: content_,
            transformResponse: [],
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http(options_).then((_response) => {
            return this.processAddProperty(_response);
        }, (_response) => {
            if (_response.status)
                return this.processAddProperty(_response);
            throw _response;
        });
    }

    protected processAddProperty(response: any): ng.IPromise<void> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            return this.q.resolve<void>(<any>null);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<void>(<any>null);
    }

    removeProperty(id: string, name: string | null): ng.IPromise<void> {
        let url_ = this.baseUrl + "/api/ValueObjects/{id}/properties/{name}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (name === undefined || name === null)
            throw new Error("The parameter 'name' must be defined.");
        url_ = url_.replace("{name}", encodeURIComponent("" + name));
        url_ = url_.replace(/[?&]$/, "");

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "DELETE",
            transformResponse: [],
            headers: {
            }
        };

        return this.http(options_).then((_response) => {
            return this.processRemoveProperty(_response);
        }, (_response) => {
            if (_response.status)
                return this.processRemoveProperty(_response);
            throw _response;
        });
    }

    protected processRemoveProperty(response: any): ng.IPromise<void> {
        const status = response.status;

        let _headers: any = {};
        if (status === 200) {
            const _responseText = response.data;
            return this.q.resolve<void>(<any>null);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText, _headers);
        }
        return this.q.resolve<void>(<any>null);
    }
}

export class BaseType implements IBaseType {
    id?: string;
    name?: string | undefined;
    description?: string | undefined;

    constructor(data?: IBaseType) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.name = _data["Name"];
            this.description = _data["Description"];
        }
    }

    static fromJS(data: any): BaseType {
        data = typeof data === 'object' ? data : {};
        let result = new BaseType();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["Name"] = this.name;
        data["Description"] = this.description;
        return data; 
    }
}

export interface IBaseType {
    id?: string;
    name?: string | undefined;
    description?: string | undefined;
}

export class DomainEventDetails extends BaseType implements IDomainEventDetails {
    properties?: Property[] | undefined;

    constructor(data?: IDomainEventDetails) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["Properties"])) {
                this.properties = [] as any;
                for (let item of _data["Properties"])
                    this.properties!.push(Property.fromJS(item));
            }
        }
    }

    static fromJS(data: any): DomainEventDetails {
        data = typeof data === 'object' ? data : {};
        let result = new DomainEventDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.properties)) {
            data["Properties"] = [];
            for (let item of this.properties)
                data["Properties"].push(item.toJSON());
        }
        super.toJSON(data);
        return data; 
    }
}

export interface IDomainEventDetails extends IBaseType {
    properties?: Property[] | undefined;
}

export class Property implements IProperty {
    name?: string | undefined;
    description?: string | undefined;
    isCollection?: boolean;
    isIdentity?: boolean;
    systemType?: SystemType | undefined;
    valueType?: ValueObject | undefined;

    constructor(data?: IProperty) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["Name"];
            this.description = _data["Description"];
            this.isCollection = _data["IsCollection"];
            this.isIdentity = _data["IsIdentity"];
            this.systemType = _data["SystemType"];
            this.valueType = _data["ValueType"] ? ValueObject.fromJS(_data["ValueType"]) : <any>undefined;
        }
    }

    static fromJS(data: any): Property {
        data = typeof data === 'object' ? data : {};
        let result = new Property();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Name"] = this.name;
        data["Description"] = this.description;
        data["IsCollection"] = this.isCollection;
        data["IsIdentity"] = this.isIdentity;
        data["SystemType"] = this.systemType;
        data["ValueType"] = this.valueType ? this.valueType.toJSON() : <any>undefined;
        return data; 
    }
}

export interface IProperty {
    name?: string | undefined;
    description?: string | undefined;
    isCollection?: boolean;
    isIdentity?: boolean;
    systemType?: SystemType | undefined;
    valueType?: ValueObject | undefined;
}

export enum SystemType {
    String = "String",
    Number = "Number",
    Boolean = "Boolean",
}

export class ValueObject extends BaseType implements IValueObject {

    constructor(data?: IValueObject) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): ValueObject {
        data = typeof data === 'object' ? data : {};
        let result = new ValueObject();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface IValueObject extends IBaseType {
}

export class GeneratedCodeOfDomainEvent implements IGeneratedCodeOfDomainEvent {
    model?: DomainEvent | undefined;
    template?: Template | undefined;
    value?: string | undefined;

    constructor(data?: IGeneratedCodeOfDomainEvent) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.model = _data["Model"] ? DomainEvent.fromJS(_data["Model"]) : <any>undefined;
            this.template = _data["Template"] ? Template.fromJS(_data["Template"]) : <any>undefined;
            this.value = _data["Value"];
        }
    }

    static fromJS(data: any): GeneratedCodeOfDomainEvent {
        data = typeof data === 'object' ? data : {};
        let result = new GeneratedCodeOfDomainEvent();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Model"] = this.model ? this.model.toJSON() : <any>undefined;
        data["Template"] = this.template ? this.template.toJSON() : <any>undefined;
        data["Value"] = this.value;
        return data; 
    }
}

export interface IGeneratedCodeOfDomainEvent {
    model?: DomainEvent | undefined;
    template?: Template | undefined;
    value?: string | undefined;
}

export class DomainEvent extends BaseType implements IDomainEvent {

    constructor(data?: IDomainEvent) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): DomainEvent {
        data = typeof data === 'object' ? data : {};
        let result = new DomainEvent();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface IDomainEvent extends IBaseType {
}

export class Template implements ITemplate {
    id?: string;
    name?: string | undefined;
    metaType?: MetaType;
    value?: string | undefined;

    constructor(data?: ITemplate) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.name = _data["Name"];
            this.metaType = _data["MetaType"];
            this.value = _data["Value"];
        }
    }

    static fromJS(data: any): Template {
        data = typeof data === 'object' ? data : {};
        let result = new Template();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["Name"] = this.name;
        data["MetaType"] = this.metaType;
        data["Value"] = this.value;
        return data; 
    }
}

export interface ITemplate {
    id?: string;
    name?: string | undefined;
    metaType?: MetaType;
    value?: string | undefined;
}

export enum MetaType {
    Module = "Module",
    Entity = "Entity",
    ValueObject = "ValueObject",
    DomainEvent = "DomainEvent",
}

export class AddProperty implements IAddProperty {
    name!: string;
    description?: string | undefined;
    isCollection?: boolean;
    isIdentity?: boolean;
    systemType?: SystemType | undefined;
    valueTypeId?: string | undefined;

    constructor(data?: IAddProperty) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["Name"];
            this.description = _data["Description"];
            this.isCollection = _data["IsCollection"];
            this.isIdentity = _data["IsIdentity"];
            this.systemType = _data["SystemType"];
            this.valueTypeId = _data["ValueTypeId"];
        }
    }

    static fromJS(data: any): AddProperty {
        data = typeof data === 'object' ? data : {};
        let result = new AddProperty();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Name"] = this.name;
        data["Description"] = this.description;
        data["IsCollection"] = this.isCollection;
        data["IsIdentity"] = this.isIdentity;
        data["SystemType"] = this.systemType;
        data["ValueTypeId"] = this.valueTypeId;
        return data; 
    }
}

export interface IAddProperty {
    name: string;
    description?: string | undefined;
    isCollection?: boolean;
    isIdentity?: boolean;
    systemType?: SystemType | undefined;
    valueTypeId?: string | undefined;
}

export class Entity extends BaseType implements IEntity {
    isAggregateRoot?: boolean;

    constructor(data?: IEntity) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.isAggregateRoot = _data["IsAggregateRoot"];
        }
    }

    static fromJS(data: any): Entity {
        data = typeof data === 'object' ? data : {};
        let result = new Entity();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["IsAggregateRoot"] = this.isAggregateRoot;
        super.toJSON(data);
        return data; 
    }
}

export interface IEntity extends IBaseType {
    isAggregateRoot?: boolean;
}

export class EntityDetails extends Entity implements IEntityDetails {
    properties?: Property[] | undefined;
    domainEvents?: DomainEvent[] | undefined;
    relations?: EntityRelation[] | undefined;

    constructor(data?: IEntityDetails) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["Properties"])) {
                this.properties = [] as any;
                for (let item of _data["Properties"])
                    this.properties!.push(Property.fromJS(item));
            }
            if (Array.isArray(_data["DomainEvents"])) {
                this.domainEvents = [] as any;
                for (let item of _data["DomainEvents"])
                    this.domainEvents!.push(DomainEvent.fromJS(item));
            }
            if (Array.isArray(_data["Relations"])) {
                this.relations = [] as any;
                for (let item of _data["Relations"])
                    this.relations!.push(EntityRelation.fromJS(item));
            }
        }
    }

    static fromJS(data: any): EntityDetails {
        data = typeof data === 'object' ? data : {};
        let result = new EntityDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.properties)) {
            data["Properties"] = [];
            for (let item of this.properties)
                data["Properties"].push(item.toJSON());
        }
        if (Array.isArray(this.domainEvents)) {
            data["DomainEvents"] = [];
            for (let item of this.domainEvents)
                data["DomainEvents"].push(item.toJSON());
        }
        if (Array.isArray(this.relations)) {
            data["Relations"] = [];
            for (let item of this.relations)
                data["Relations"].push(item.toJSON());
        }
        super.toJSON(data);
        return data; 
    }
}

export interface IEntityDetails extends IEntity {
    properties?: Property[] | undefined;
    domainEvents?: DomainEvent[] | undefined;
    relations?: EntityRelation[] | undefined;
}

export class EntityRelation implements IEntityRelation {
    name?: string | undefined;
    description?: string | undefined;
    toEntity?: Entity | undefined;
    multiplicity?: Multiplicity;

    constructor(data?: IEntityRelation) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["Name"];
            this.description = _data["Description"];
            this.toEntity = _data["ToEntity"] ? Entity.fromJS(_data["ToEntity"]) : <any>undefined;
            this.multiplicity = _data["Multiplicity"];
        }
    }

    static fromJS(data: any): EntityRelation {
        data = typeof data === 'object' ? data : {};
        let result = new EntityRelation();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Name"] = this.name;
        data["Description"] = this.description;
        data["ToEntity"] = this.toEntity ? this.toEntity.toJSON() : <any>undefined;
        data["Multiplicity"] = this.multiplicity;
        return data; 
    }
}

export interface IEntityRelation {
    name?: string | undefined;
    description?: string | undefined;
    toEntity?: Entity | undefined;
    multiplicity?: Multiplicity;
}

export enum Multiplicity {
    One = "One",
    Many = "Many",
}

export class GeneratedCodeOfEntity implements IGeneratedCodeOfEntity {
    model?: Entity | undefined;
    template?: Template | undefined;
    value?: string | undefined;

    constructor(data?: IGeneratedCodeOfEntity) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.model = _data["Model"] ? Entity.fromJS(_data["Model"]) : <any>undefined;
            this.template = _data["Template"] ? Template.fromJS(_data["Template"]) : <any>undefined;
            this.value = _data["Value"];
        }
    }

    static fromJS(data: any): GeneratedCodeOfEntity {
        data = typeof data === 'object' ? data : {};
        let result = new GeneratedCodeOfEntity();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Model"] = this.model ? this.model.toJSON() : <any>undefined;
        data["Template"] = this.template ? this.template.toJSON() : <any>undefined;
        data["Value"] = this.value;
        return data; 
    }
}

export interface IGeneratedCodeOfEntity {
    model?: Entity | undefined;
    template?: Template | undefined;
    value?: string | undefined;
}

export class CreateType implements ICreateType {
    moduleId!: string;
    name!: string;
    description!: string;

    constructor(data?: ICreateType) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.moduleId = _data["ModuleId"];
            this.name = _data["Name"];
            this.description = _data["Description"];
        }
    }

    static fromJS(data: any): CreateType {
        data = typeof data === 'object' ? data : {};
        let result = new CreateType();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["ModuleId"] = this.moduleId;
        data["Name"] = this.name;
        data["Description"] = this.description;
        return data; 
    }
}

export interface ICreateType {
    moduleId: string;
    name: string;
    description: string;
}

export class AddDomainEvent implements IAddDomainEvent {
    name!: string;
    description?: string | undefined;

    constructor(data?: IAddDomainEvent) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["Name"];
            this.description = _data["Description"];
        }
    }

    static fromJS(data: any): AddDomainEvent {
        data = typeof data === 'object' ? data : {};
        let result = new AddDomainEvent();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Name"] = this.name;
        data["Description"] = this.description;
        return data; 
    }
}

export interface IAddDomainEvent {
    name: string;
    description?: string | undefined;
}

export class AddRelation implements IAddRelation {
    name!: string;
    description?: string | undefined;
    toEntityId!: string;
    multiplicity?: Multiplicity;

    constructor(data?: IAddRelation) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["Name"];
            this.description = _data["Description"];
            this.toEntityId = _data["ToEntityId"];
            this.multiplicity = _data["Multiplicity"];
        }
    }

    static fromJS(data: any): AddRelation {
        data = typeof data === 'object' ? data : {};
        let result = new AddRelation();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Name"] = this.name;
        data["Description"] = this.description;
        data["ToEntityId"] = this.toEntityId;
        data["Multiplicity"] = this.multiplicity;
        return data; 
    }
}

export interface IAddRelation {
    name: string;
    description?: string | undefined;
    toEntityId: string;
    multiplicity?: Multiplicity;
}

export class Module implements IModule {
    id?: string;
    name?: string | undefined;
    description?: string | undefined;
    entities?: Entity[] | undefined;
    valueObjects?: ValueObject[] | undefined;

    constructor(data?: IModule) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.name = _data["Name"];
            this.description = _data["Description"];
            if (Array.isArray(_data["Entities"])) {
                this.entities = [] as any;
                for (let item of _data["Entities"])
                    this.entities!.push(Entity.fromJS(item));
            }
            if (Array.isArray(_data["ValueObjects"])) {
                this.valueObjects = [] as any;
                for (let item of _data["ValueObjects"])
                    this.valueObjects!.push(ValueObject.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Module {
        data = typeof data === 'object' ? data : {};
        let result = new Module();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["Name"] = this.name;
        data["Description"] = this.description;
        if (Array.isArray(this.entities)) {
            data["Entities"] = [];
            for (let item of this.entities)
                data["Entities"].push(item.toJSON());
        }
        if (Array.isArray(this.valueObjects)) {
            data["ValueObjects"] = [];
            for (let item of this.valueObjects)
                data["ValueObjects"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IModule {
    id?: string;
    name?: string | undefined;
    description?: string | undefined;
    entities?: Entity[] | undefined;
    valueObjects?: ValueObject[] | undefined;
}

export class GeneratedCodeOfModule implements IGeneratedCodeOfModule {
    model?: Module | undefined;
    template?: Template | undefined;
    value?: string | undefined;

    constructor(data?: IGeneratedCodeOfModule) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.model = _data["Model"] ? Module.fromJS(_data["Model"]) : <any>undefined;
            this.template = _data["Template"] ? Template.fromJS(_data["Template"]) : <any>undefined;
            this.value = _data["Value"];
        }
    }

    static fromJS(data: any): GeneratedCodeOfModule {
        data = typeof data === 'object' ? data : {};
        let result = new GeneratedCodeOfModule();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Model"] = this.model ? this.model.toJSON() : <any>undefined;
        data["Template"] = this.template ? this.template.toJSON() : <any>undefined;
        data["Value"] = this.value;
        return data; 
    }
}

export interface IGeneratedCodeOfModule {
    model?: Module | undefined;
    template?: Template | undefined;
    value?: string | undefined;
}

export class CreateModule implements ICreateModule {
    name!: string;
    description!: string;
    parentModuleId?: string | undefined;

    constructor(data?: ICreateModule) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["Name"];
            this.description = _data["Description"];
            this.parentModuleId = _data["ParentModuleId"];
        }
    }

    static fromJS(data: any): CreateModule {
        data = typeof data === 'object' ? data : {};
        let result = new CreateModule();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Name"] = this.name;
        data["Description"] = this.description;
        data["ParentModuleId"] = this.parentModuleId;
        return data; 
    }
}

export interface ICreateModule {
    name: string;
    description: string;
    parentModuleId?: string | undefined;
}

export class CreateTemplate implements ICreateTemplate {
    metaType?: MetaType;
    name!: string;
    value!: string;

    constructor(data?: ICreateTemplate) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.metaType = _data["MetaType"];
            this.name = _data["Name"];
            this.value = _data["Value"];
        }
    }

    static fromJS(data: any): CreateTemplate {
        data = typeof data === 'object' ? data : {};
        let result = new CreateTemplate();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["MetaType"] = this.metaType;
        data["Name"] = this.name;
        data["Value"] = this.value;
        return data; 
    }
}

export interface ICreateTemplate {
    metaType?: MetaType;
    name: string;
    value: string;
}

export class UpdateTemplate implements IUpdateTemplate {
    value!: string;

    constructor(data?: IUpdateTemplate) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.value = _data["Value"];
        }
    }

    static fromJS(data: any): UpdateTemplate {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateTemplate();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Value"] = this.value;
        return data; 
    }
}

export interface IUpdateTemplate {
    value: string;
}

export class ValueObjectDetails extends BaseType implements IValueObjectDetails {
    properties?: Property[] | undefined;

    constructor(data?: IValueObjectDetails) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["Properties"])) {
                this.properties = [] as any;
                for (let item of _data["Properties"])
                    this.properties!.push(Property.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ValueObjectDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ValueObjectDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.properties)) {
            data["Properties"] = [];
            for (let item of this.properties)
                data["Properties"].push(item.toJSON());
        }
        super.toJSON(data);
        return data; 
    }
}

export interface IValueObjectDetails extends IBaseType {
    properties?: Property[] | undefined;
}

export class GeneratedCodeOfValueObject implements IGeneratedCodeOfValueObject {
    model?: ValueObject | undefined;
    template?: Template | undefined;
    value?: string | undefined;

    constructor(data?: IGeneratedCodeOfValueObject) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.model = _data["Model"] ? ValueObject.fromJS(_data["Model"]) : <any>undefined;
            this.template = _data["Template"] ? Template.fromJS(_data["Template"]) : <any>undefined;
            this.value = _data["Value"];
        }
    }

    static fromJS(data: any): GeneratedCodeOfValueObject {
        data = typeof data === 'object' ? data : {};
        let result = new GeneratedCodeOfValueObject();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Model"] = this.model ? this.model.toJSON() : <any>undefined;
        data["Template"] = this.template ? this.template.toJSON() : <any>undefined;
        data["Value"] = this.value;
        return data; 
    }
}

export interface IGeneratedCodeOfValueObject {
    model?: ValueObject | undefined;
    template?: Template | undefined;
    value?: string | undefined;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(q: ng.IQService, message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): ng.IPromise<any> {
    if (result !== null && result !== undefined)
        return q.reject(result);
    else
        return q.reject(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: Blob, q: ng.IQService): ng.IPromise<string> {
    return new q((resolve) => {
        let reader = new FileReader();
        reader.onload = event => resolve((<any>event.target).result);
        reader.readAsText(blob);
    });
}